# create super user
POST http://localhost:5500/api/create-superuser HTTP/1.1
Content-Type: application/json

{
    "name":"Aryan Sanjay Nipane",
    "username":"superuser",
    "password":"superuser"
}

###

# login-superuser
POST http://localhost:5500/api/login-superuser HTTP/1.1
Content-Type: application/json

{
    "username":"nipanearyan",
    "password":"0po3nsf*3&@"
}

###

# create admin
POST http://localhost:5500/api/create-admin HTTP/1.1
Content-Type: application/json

{
    "name":"Aryan Nipane",
    "username":"nipanearyan",
    "password":"0po3nsf*3&@"
}

###

# get all admins
POST http://localhost:5500/api/get-admins HTTP/1.1
Content-Type: application/json

{}

###

# remove admin
POST http://localhost:5500/api/remove-admin HTTP/1.1
Content-Type: application/json

{
    "id":"62f7ee9041dbd708b0eb64c8"
}

###

# refresh auth
GET http://localhost:5500/api/refresh HTTP/1.1
Content-Type: application/json

{}










###

# testing route not the part of project
POST http://localhost:5500/api/test HTTP/1.1
Content-Type: application/json

{
    "username":"nipanearyan"
}